analyzer/urls.py
from django.urls import path

from . import views

app_name = 'analyzer'

urlpatterns = [
    path('', views.analyze, name='analyze'),
    path('/<str:ingredients_correction>/<str:meal_url_correction>/<str:language>/', views.analyze, name='analyze'),
    path('/<str:ingredients_correction>/<str:language>/', views.analyze, name='analyze'),
]

cards/urls.py
from django.urls import include, path

from . import views

app_name = 'cards'

urlpatterns = [

    path('create/?meal_name=<str:meal_name>/?meal_url=<str:meal_url>/?ingredients=<str:ingredients>/?results=<results>/?meal_images=<meal_images>/?safety=<safety>/?tokens=<str:tokens>/',
         views.meal_create, name='meal_create'),
    path('create/', views.meal_create, name='meal_create'),
    path('details/<int:id>/', views.meal_details, name='meal_details'),
    path('edit/<int:pk>/', views.edit, name='meal_edit'),
    path('meals_list/', views.meals_list, name='meals_list'),
    path('collect/', views.collect, name='collect')


]

fodmap_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import credits

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analyzer.urls', namespace="analyzer")),
    path('credits/', credits, name='credits'),
    path('users/', include('users.urls', namespace="users")),
    path('meals/', include('cards.urls', namespace="cards")),
    path('search/', include('search.urls', namespace="search")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(),  name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('profile/pass_change/', views.PasswordChange.as_view(), name='password_change'),
]

analyzer/models.py
from django.db import models

# Create your models here.

analyzer/forms.py
from django import forms


class LanguageForm(forms.Form):
    CHOICES = [('ENG', 'English'), ('PL', 'Polski')]
    language = forms.ChoiceField(choices=CHOICES,  required=True, label='Select language: ')

class IngredientsForm(forms.Form):
    ingredients = forms.CharField(label='Ingredients: ', widget=forms.Textarea, required=False)

class LinkForm(forms.Form):
    link = forms.URLField(label='or link to the recipe: ', required=False)

analyzer/views.py
from urllib import parse

from django.contrib.postgres.search import SearchVector
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from cards.models import Meal
from search.forms import SearchForm
from universal.slug import slug

from .forms import IngredientsForm, LanguageForm, LinkForm
from .utils.ingredients_checker import IngredientsChecker
from .utils.safety import calculate_safety
from .utils.scraper import Scraper
from .utils.stemmer import stemm




def get_website_data(link_form):
        scraper = Scraper()
        meal = scraper.parse(link_form['link'].value())
        meal_name = slug(str(meal.name).replace(',', '').replace('/\n', '').replace("'", '').strip(), True)
        meal_url = parse.quote(meal.url, safe='')
        meal_images = slug(str([parse.quote(img, safe='') for img in meal.images]), True) if len(meal.images) > 1 \
            else parse.quote(str(meal.images), safe='')
        return {'meal': meal, 'meal_name': meal_name, 'meal_url': meal_url, 'meal_images': meal_images}


def get_results(ingredients, language):
    checker = IngredientsChecker(ingredients)
    results, not_found, ingredients, stems = checker.check_ingredients(language)
    stems = slug(str(stems), True)
    safety = slug(str(calculate_safety(results)), True)
    safety_table = calculate_safety(results)
    return {'results': results, 'not_found': not_found, 'ingredients': ingredients, 'stems': stems, 'safety': safety,
            'safety_table': safety_table}


def analyze(request, ingredients_correction=None, meal_url_correction=None, language=None):
    meals = Meal.objects.all().order_by('-created')
    paginator = Paginator(meals, 6)
    page = request.GET.get('page')
    try:
        meals = paginator.page(page)
    except PageNotAnInteger:
        meals = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        meals = paginator.page(paginator.num_pages)
    # meals = Meal.objects.all().order_by('-created')[0:3]
    search_form = SearchForm()
    meal_data = dict()
    results_data = dict()
    ingredients_save, results_save= None, None
    language = request.POST.get('language') if not language or request.POST.get('language') != language else language
    if request.method == 'POST':
        language_form = LanguageForm(request.POST)
        ingr_form = IngredientsForm(request.POST)
        link_form = LinkForm(request.POST)
        if ingr_form.data['ingredients']:
            if ingr_form.is_valid():
                if link_form.data['link']:
                    meal_data = get_website_data(link_form)
                results_data = get_results(ingr_form['ingredients'].value(), language)
        elif link_form.data['link']:
            if link_form.is_valid():
                meal_data = get_website_data(link_form)
                results_data = get_results(meal_data['meal'].ingredients.split('\n'), language)
        if results_data:
            results_save = parse.quote(slug(str(results_data.get('results')), True), safe='')
            ingredients_save = parse.quote(slug('\n'.join(results_data.get('ingredients', '')), True), safe='')
    else:
        language_form = LanguageForm()
        ingr_form = IngredientsForm()
        link_form = LinkForm()
        if ingredients_correction:
            ingr_form.fields['ingredients'].initial = parse.unquote(slug(ingredients_correction, False))
            if meal_url_correction and meal_url_correction != "None":
                link_form.fields['link'].initial = parse.unquote(meal_url_correction)
            language_form.fields['language'].initial = language
    if request.is_ajax():
            return render(request, 'meals_list_ajax.html', {'meals': meals})
    return render(request, 'analyzer/analyze.html',
                  {'language_form': language_form, 'ingr_form': ingr_form, 'link_form': link_form, 'language': language,
                   #this is for results table
                   'ingredients': results_data.get('ingredients', None),
                   'results': results_data.get('results', None), 'not_found': results_data.get('not_found', None),
                   'safety_table': results_data.get('safety_table', None),
                   # this is for saving form
                   'meal_name': meal_data.get('meal_name', None), 'meal_url': meal_data.get('meal_url', None),
                   'meal_images': meal_data.get('meal_images', None),
                   'ingredients_save': ingredients_save, 'results_save': results_save,
                   'meals': meals, 'safety': results_data.get('safety', None),
                   'tokens': results_data.get('stems', None),
                   'search_form': search_form })


def meals_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            token = stemm(query)
            results = Meal.objects.annotate(search=SearchVector('meal_name', 'ingredients', 'tokens'),).filter(search=token[0])
            for word in token:
                results = results | Meal.objects.annotate(search=SearchVector('meal_name', 'ingredients', 'tokens'),).filter(search=word)
    return render(request, 'analyzer/search.html', {'form': form, 'query': query, 'results': results})

analyzer/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Spectral:300|Roboto:300,400&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Is that low fodmap?</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-light pt-1 pb-2">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'analyzer:analyze' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="btn btn-round nav-link bg-greybeige font-small" href="{% url 'credits' %}">i</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="{% url 'analyzer:analyze' %}"><div class="text-center">
            <img src="{% static 'images/pineapple.svg' %}" class="h-30"><br>
            <span class="font-spectral text-center">is that low fodmap?</span>
        </div></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2 mr-5">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            {% else %}

            <div class="dropdown mr-150px">
                <a href="." class="dropdown-toggle text-dark" data-toggle="dropdown"><b>Log in</b></a>
                <ul id="login-dp" class="dropdown-menu pb-4">
                    <li>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="login-register">
                                    <!--                                    Login using-->
                                    <!--                                    <div class="social-buttons">-->
                                    <!--                                    <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>-->
                                    <!--                                    <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>-->
                                    <!--                                    </div>-->
                                    <!--                                    or-->
                                    <form class="form" role="form" method="POST" action="{% url 'users:login' %}" accept-charset="UTF-8" id="login-nav">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="id_username">Username</label>
                                            <input type='text' class="form-control" id="id_username" name="username" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_password">Password</label>
                                            <input type="password" class="form-control" id="id_password" name="password" required>
                                            <!--                                            <div class="help-block text-right"><a href="">Zapomniałeś/aś hasła?</a></div>-->
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-dark btn-block">Login</button>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> Nie wylogowuj mnie
                                            </label>
                                            <br /> <br />
                                            Don't have an account yet?<br />
                                            <button id="action_button" class="btn btn-dark btn-block"><a href="{% url 'users:register' %}" class="text-white ">Singup</a></button>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>

                    </li>
                </ul>
            </div>
            {% endif %}
        </ul>
    </div>
</nav>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">x</a>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% block main_columns %}
{% endblock main_columns %}

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"> </script>
<script>
  var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method)); }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });

  $(document).ready(function(){
    {% block domready %}
    {% endblock domready %}
    });
</script>
</body>
</html>

analyzer/templates/main_columns.html
{% extends 'base.html' %}
{% load static %}

{% block main_columns %}
<div class="container-fluid mt-5 oh bg-greybeige">

    <div class="row d-flex flex-wrap align-items-center bg-pineapple minh-60 no-gutters">
        {% block row %}
        {% endblock row %}
    </div>

</div>
{% endblock main_columns %}

analyzer/templates/meals_list_ajax.html
{% load analyzer_extras %}
{% load cards_extras %}
{% for meal in meals %}
<div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 pb-3 pt-3 text-center hover-dark">
    <a href="{{ meal.get_absolute_url }} ">
        <img src="{{ meal.image_file.url }}"
             class="img-thumb" alt="{{ meal.meal_name|capfirst }}">
        <p class="mt-3">{% for colour in meal.safety|evaluate_list %}{% for key, value in colour.items %}{% for i in value|make_range %}<span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>{% endfor %}{% endfor %}{% endfor %} </p>
        <p class=""> {{ meal.meal_name|lower|capfirst|linebreaks }} </p></a>
</div>
{% endfor %}