cards/urls.py
from django.urls import include, path

from . import views

app_name = 'cards'

urlpatterns = [

    path('create/?meal_name=<str:meal_name>/?meal_url=<str:meal_url>/?ingredients=<str:ingredients>/?results=<results>/?meal_images=<meal_images>/?safety=<safety>/?tokens=<str:tokens>/',
         views.meal_create, name='meal_create'),
    path('create/', views.meal_create, name='meal_create'),
    path('details/<int:id>/', views.meal_details, name='meal_details'),
    path('edit/<int:pk>/', views.edit, name='meal_edit'),
    path('meals_list/', views.meals_list, name='meals_list'),
    path('collect/', views.collect, name='collect')


]

fodmap_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import credits

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analyzer.urls', namespace="analyzer")),
    path('credits/', credits, name='credits'),
    path('users/', include('users.urls', namespace="users")),
    path('meals/', include('cards.urls', namespace="cards")),
    path('search/', include('search.urls', namespace="search")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(),  name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('profile/pass_change/', views.PasswordChange.as_view(), name='password_change'),
]

users/models.py
from django.conf import settings
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserEditForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render

from cards.models import Meal

from .forms import LoginForm, UserEditForm, UserRegistrationForm
from .models import Profile


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            Profile.objects.create(user=new_user)
            # login user
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('analyzer:analyze')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

def user_login(request):
    next_page = request.GET['next']
    if request.user.is_authenticated():
        return HttpResponseRedirect(next_page)
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user = authenticate(request, username=cd['username'], password=cd['password'])
                if user is not None:
                    login(request, user)
                    if next_page:
                        return HttpResponseRedirect(next_page)
                    else:
                        return HttpResponseRedirect('/')
                else:
                    error_msg = 'Could not log in'
                    return render(request, "login", {'form': form, 'error_msg': error_msg})
            else:
                error_msg = "Invalid credentials"
                return render(request, "login", {'form': form, 'error_msg': error_msg})
        else:
            form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def profile(request):
    meals = Meal.objects.filter(collectors=request.user)
    saved = Meal.objects.filter(author=request.user).count()
    collected = Meal.objects.filter(collectors=request.user).count()-saved
    paginator = Paginator(meals, 6)
    page = request.GET.get('page')
    try:
        meals = paginator.page(page)
    except PageNotAnInteger:
        meals = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        meals = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'users/user_list_ajax.html', {'meals': meals})
    return render(request, 'users/profile.html', {'meals': meals, 'collected': collected, 'saved':saved})


@login_required
def profile_edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('/users/profile')
        else:
            messages.error(request, "Your profile could not be updated")
    else:
        user_form = UserEditForm(instance=request.user)
    return render(request, 'users/profile_edit.html', {'user_form': user_form})


class PasswordChange(PasswordChangeView):
    success_url = '/users/profile'
    template_name = 'users/password_change.html'


def credits(request):
    return render(request, 'credits.html')

users/templates/users/password_change.html
{% extends 'main_columns.html' %}

{% load analyzer_extras %}
{% load cards_extras %}

{% load crispy_forms_tags %}

{% block row %}
<div class="col"></div>
<div class="col text-center"><h2> Change your password </h2>
    <form action='.' method="post" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <p><input type="submit" value="Save"></p>
    </form>
</div>
<div class="col"></div>
{% endblock row %}

users/templates/users/profile.html
{% extends 'main_columns.html' %}

{% load analyzer_extras %}
{% load cards_extras %}


{% block row %}
<div class="col"></div>
<div class="col text-center"><h2> {{ user.username|capfirst }} </h2>
    You collected  {{ collected }} meal{{ collected|pluralize }} and saved {{ saved }} meal{{ saved|pluralize }}.
    <a href="{% url 'users:profile_edit' %}" class="d-block pt-5">Edit your profile</a>
    <a href="{% url 'users:password_change' %}" class="d-block">Change password</a>
</div>
<div class="col">
</div>
{% endblock row %}
{% block content %}

<div class="container">
    <h2 class="p-3 mt-3 text-center font-spectral"> Here is your meals collection </h2>
    <div class="row" id="meals-list">
        {% include 'users/user_list_ajax.html' %}
    </div>

</div>
{% endblock content %}


{% block domready %}
var page = 1;
var empty_page = false;
var block_request = false;
$(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data) {
            if(data == '') {
                empty_page = true;
            } else {
                block_request = false;
                $('#meals-list').append(data);
            }
        });
    }
});
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'main_columns.html' %}

{% load analyzer_extras %}
{% load cards_extras %}

{% load crispy_forms_tags %}

{% block row %}
<div class="col"></div>
<div class="col text-center"><h2> Edit your profile </h2>
    <form action='.' method="post" enctype="multipart/form-data">
        {{ user_form|crispy }}
        {% csrf_token %}
        <p><input type="submit" value="Save" class="btn btn-dark"></p>
    </form>
</div>
<div class="col"></div>
{% endblock row %}

users/templates/users/user_list_ajax.html
{% load analyzer_extras %}
{% load cards_extras %}
{% for meal in meals %}
<div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 pb-3 pt-3 text-center hover-dark">
    <a href="{{ meal.get_absolute_url }} ">
        <img src="{{ meal.image_file.url }}"
             class="img-thumb" alt="{{ meal.meal_name|capfirst }}">
        <p class="mt-3">{% for colour in meal.safety|evaluate_list %}{% for key, value in colour.items %}{% for i in value|make_range %}<span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>{% endfor %}{% endfor %}{% endfor %} </p>
        <p class=""> {{ meal.meal_name|lower|capfirst|linebreaks }} </p></a>
</div>
{% endfor %}

users/templates/users/user_meals.html
{% extends 'main_columns.html' %}
{% load analyzer_extras %}
{% load cards_extras %}


{% block row %}
<div class="text-center">
  {% include 'users/profile.html' with user=user %}
  <h1 class="font-spectral"> </h1>
</div>
{% endblock row %}

{% block content %}
<h3 class="text-center pt-5">Here are the meals you have saved:</h3>

<div class="container">
  <div class="row">
    {% for meal in object_list %}
    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 pb-3 pt-3 text-center hover-dark">
      <a href="{{ meal.get_absolute_url }} ">
        <img src="{{ meal.image_file.url }}"
             class="img-thumb" alt="{{ meal.meal_name|capfirst }}">
        <p class="mt-3">{% for colour in meal.safety|evaluate_list %}{% for key, value in colour.items %}{% for i in value|make_range %}<span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>{% endfor %}{% endfor %}{% endfor %} </p>
        <p class=""> {{ meal.meal_name|lower|capfirst|linebreaks }} </p></a>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock content %}

users/templates/users/user_meals1.html
{% extends 'main_columns.html' %}
{% load analyzer_extras %}
{% load cards_extras %}


{% block row %}
<div class="text-center">
  {% include 'users/profile.html' with user=user %}
  <h1 class="font-spectral"> </h1>
</div>
{% endblock row %}

{% block content %}
<h3 class="text-center pt-5">Here are the meals you have saved:</h3>

<div class="container">
  <div class="row">
    {% for meal in object_list %}
    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 pb-3 pt-3 text-center hover-dark">
      <a href="{{ meal.get_absolute_url }} ">
        <img src="{{ meal.image_file.url }}"
             class="img-thumb" alt="{{ meal.meal_name|capfirst }}">
        <p class="mt-3">{% for colour in meal.safety|evaluate_list %}{% for key, value in colour.items %}{% for i in value|make_range %}<span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>{% endfor %}{% endfor %}{% endfor %} </p>
        <p class=""> {{ meal.meal_name|lower|capfirst|linebreaks }} </p></a>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock content %}