cards/urls.py
from django.urls import include, path

from . import views

app_name = 'cards'

urlpatterns = [

    path('create/?meal_name=<str:meal_name>/?meal_url=<str:meal_url>/?ingredients=<str:ingredients>/?results=<results>/?meal_images=<meal_images>/?safety=<safety>/?tokens=<str:tokens>/',
         views.meal_create, name='meal_create'),
    path('create/', views.meal_create, name='meal_create'),
    path('details/<int:id>/', views.meal_details, name='meal_details'),
    path('edit/<int:pk>/', views.edit, name='meal_edit'),
    path('meals_list/', views.meals_list, name='meals_list'),
    path('collect/', views.collect, name='collect')


]

fodmap_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import credits

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analyzer.urls', namespace="analyzer")),
    path('credits/', credits, name='credits'),
    path('users/', include('users.urls', namespace="users")),
    path('meals/', include('cards.urls', namespace="cards")),
    path('search/', include('search.urls', namespace="search")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(),  name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('profile/pass_change/', views.PasswordChange.as_view(), name='password_change'),
]

cards/models.py
import os
from io import StringIO
from tempfile import NamedTemporaryFile
from urllib import request
from urllib.request import Request, urlopen

import requests
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.files import File
from django.core.files.base import ContentFile
from django.core.files.images import ImageFile
from django.db import models
from django.urls import reverse
from PIL import Image

from analyzer.utils.safety import calculate_safety


def get_admin_user():
    return get_user_model().objects.get_or_create(username='inez')

class Meal(models.Model):
    meal_name = models.CharField(max_length=100)
    ingredients = models.TextField()
    tokens = models.TextField(blank=True)
    results = models.TextField(blank=True)
    safety =  models.TextField(blank=True)
    meal_url = models.URLField(blank=True)
    image_file = models.ImageField(default='default_big.jpg', upload_to='meals_images', blank=True)
    image_url = models.URLField(blank=True, max_length=500)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET(get_admin_user))
    collectors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='meals_collected', blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.meal_name

    def get_absolute_url(self):
        return reverse('cards:meal_details', args=[self.id])

    def get_image_from_url(self, *args, **kwargs):
        if self.image_url and self.image_file.name == 'default_big.jpg':
                img_temp = NamedTemporaryFile(delete=True)
                headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5)'
                                         'AppleWebKit 537.36 (KHTML, like Gecko) Chrome',
                           'Accept': 'text/html,application/xhtml+xml,application/xml;'
                                     'q=0.9,image/webp,*/*;q=0.8'}
                req = Request(url=self.image_url, headers=headers)
                img_temp.write(urlopen(req).read())
                img_temp.flush()
                self.image_file.save(f"image_{self.meal_name}.jpg", File(img_temp))
                self.save()

    def resize_image(self):
        img = Image.open(self.image_file.path)
        if img.height > img.width:
            img = img.rotate(90, expand=True)
        if img.width > 350 or img.height > 285:
            output_size = (350, 285)
            img.thumbnail(output_size)
            img.save(self.image_file.path)

    def upload_safety(self):
        self.safety = calculate_safety(self.results)

    def save(self, *args, **kwargs):
        if self.image_url:
            self.get_image_from_url()
            # self.resize_image()
            # make aws lambda function
        self.upload_safety()
        super(Meal, self).save(*args, **kwargs)

cards/forms.py
import ast

from django import forms

from .models import Meal


class MealCreateForm(forms.ModelForm):
    meal_url = forms.URLField(required=False)

    class Meta:
        model = Meal
        fields = ['meal_name', 'safety', 'meal_url', 'image_file',  'ingredients',  'image_url', 'results', 'tokens' ]
        widgets = {
            'results': forms.TextInput(attrs={'class': 'd-none'}),
            'ingredients': forms.TextInput(attrs={'class': 'd-none'}),
            'safety': forms.TextInput(attrs={'class': 'd-none'}),
            'tokens': forms.TextInput(attrs={'class': 'd-none'}),
            'image_file': forms.FileInput}
        labels = {'results': '', 'ingredients': '', 'safety': '', 'tokens': ''}

    def clean_ingredients(self):
        cd = self.cleaned_data
        try:
            singles = [s.strip() for s in self.data.getlist('single_ingredients')]
            if len(singles) > 0:
                cd['ingredients'] = singles
        except:  # TODO what except will be caught?
            pass
        return cd['ingredients']

    def clean_results(self):
        cd = self.cleaned_data
        results = cd['results']
        ingrs = cd['ingredients']
        print("RES: ", results)
        if isinstance(results, str) and len(results)>0:
            results = ast.literal_eval(results)
        if len(ingrs) > 0:
            results = [r for r in results if r[0] in ingrs]
        return results

cards/views.py
import ast
from urllib import parse

from django import forms
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from universal.decorators import ajax_required
from universal.slug import slug

from .forms import MealCreateForm
from .models import Meal


@login_required
def meal_create(request):
    meal_url = request.POST.get('meal_url')
    meal_name = slug(request.POST.get('meal_name'), False)
    ingredients = request.POST.get('ingredients')
    meal_images = slug(request.POST.get('meal_images'), False) if request.POST.get('meal_images') else None
    results = request.POST.get('results')
    safety = slug(request.POST.get('safety'), False)
    tokens = slug(request.POST.get('tokens'), False)

    ingr_table = None
    res_table = None
    data = [meal_url, meal_name, ingredients, meal_images, results]
    try:
        ingr_table = parse.unquote(slug(ingredients, False)).split('\n')
        res_table = ast.literal_eval(parse.unquote(slug(results, False)))
    except AttributeError:
        pass

    if request.method == 'POST':
        if any(item is not None for item in data):
            form = MealCreateForm()
            if meal_name != 'None':
                form.fields['meal_name'].initial = str(meal_name).replace(',', '').replace('\\n', '').replace("'",'').strip()
            if meal_url != 'None':
                form.fields['meal_url'].initial = parse.unquote(meal_url)
            form.fields['ingredients'].initial = ingr_table
            form.fields['results'].initial = res_table
            form.fields['safety'].initial = safety
            form.fields['tokens'].initial = tokens
            if meal_images != 'None' and meal_images is not None:
                meal_images = parse.unquote(meal_images).split()
                # form.fields['image_file'].widget = forms.HiddenInput()
                # form.fields['image_url'].widget = forms.HiddenInput()
            else:
                # form.fields['image_url'].widget = forms.HiddenInput()
                meal_images = None
            if request.POST.get('save') == 'True':
                form = MealCreateForm(request.POST, request.FILES)
        else:
            form = MealCreateForm(request.POST, request.FILES)
        if form.is_valid():
            new_meal = form.save(commit=False)
            new_meal.author = request.user
            new_meal.save()
            new_meal.collectors.add(request.user)
            return redirect(new_meal.get_absolute_url())
    else:
        form = MealCreateForm()
    return render(request, 'cards/meal/create.html',
                  {'form': form, 'meal_images': meal_images, 'ingr_table': ingr_table,
                   'res_table': res_table, 'safety': safety})


def meal_details(request, id):
    meal = get_object_or_404(Meal, id=id)
    ingredients = ast.literal_eval(meal.ingredients)
    results = ast.literal_eval(parse.unquote(slug(meal.results, False)))
    safety = ast.literal_eval(meal.safety)
    is_author = True if meal.author == request.user else False
    return render(request, 'cards/meal/details.html',
                  {'meal': meal, 'results': results, 'ingredients': ingredients,
                   'safety': safety, 'is_author': is_author})


def meals_list(request):
    start = int(request.GET.get('start', 3))
    end = int(request.GET.get('end', 5))
    meals =  Meal.objects.all().order_by('-created')[start:end]
    data = serializers.serialize('json', meals,
                                 fields=('meal_name', 'meal_url', 'safety', 'image_file', 'image_url', 'safety'))
    return JsonResponse(data, safe=False)


@ajax_required
@login_required()
@require_POST
def collect(request):
    meal_id = request.POST.get('id')
    action = request.POST.get('action')
    if meal_id and action:
        try:
            meal = Meal.objects.get(id=meal_id)
            if action == 'add':
                meal.collectors.add(request.user)
            else:
                meal.collectors.remove(request.user)
        except:
            pass
    return JsonResponse({'status': 'ok'})


def edit(request, pk):
    this_meal = Meal.objects.filter(pk=pk).first()
    if request.method == 'POST':
        form = MealCreateForm(instance=this_meal, data=request.POST, files=request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            print('CD: ', cd)
            form.save()
            return redirect(this_meal.get_absolute_url())
    else:
        form = MealCreateForm(instance=this_meal)
    return render(request, 'cards/meal/meal_edit.html', {'form': form, 'meal': this_meal})

cards/templates/cards/meal/create.html
{% extends 'main_columns.html' %}
{% load static %}
{% load cards_extras %}
{% load crispy_forms_tags %}

{% block row %}

<div class="col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5  minh-60 p-2  order-sm-2 order-md-1 ">
    {% if meal_images is not None %}
    <p> Choose an image for your meal </p>
    <div id="images">
        {% for img in meal_images %}
        <img src='{{ img|cut_imgsrc }}' class="chosen image_small" data-action="unselected" />
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="col-12 col-sm-12 col-md-12 col-lg-7 col-xl-7 nice-spacer minh-60 bg-greybeige order-sm-1 order-md-2 ">

    <h1>Save a meal</h1>
    <form action="{% url 'cards:meal_create' %}" method="post" name="create_meal" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.non_field_errors }}

        {% for hidden_field in form_hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field|as_crispy_field }}
        {{ hidden_field.help_text }}
        {% endfor %}

        {% for field in form %}
        {{ field.errors }}
        {% if field.name == 'image_url' %}
        <span id="image_url"> {{ field|as_crispy_field }} </span>
        {% else %}
        {{ field|as_crispy_field }}
        {% endif %}
        {{ field.help_text }}
        {% endfor %}

        <input name="save" value="True" type="hidden">
        {% include 'analyzer/results_table.html' with ingredients=ingr_table results=res_table %}
        <div class="text-center pt-2"><input type="submit" value="Save it" class="btn btn-dark"></div>
    </form>
    <br><br>
</div>

{% endblock row %}

{% block domready %}

jQuery('#images .chosen').click(function(e){
<!--find selected image -->
selected_image = jQuery(this).attr('src');
if (selected_image.substring(0,1) == '//') {
    selected_image = 'http:'+selected_image;
}
<!--assign url of selected image to form field -->
$('#image_url input').val(selected_image);
<!--    select and unselect-->
if ($(this).data('action') == 'unselected') {
$(this).css({border: "3px solid black"})
$(this).data('action', 'selected')
} else {
$(this).css({border: "0px solid black"})
$(this).data('action', 'unselected')
}

});

{% endblock domready %}

cards/templates/cards/meal/details.html
{% extends 'main_columns.html' %}
{% load static %}
{% load analyzer_extras %}
{% block row %}


<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 order-2 order-sm-2 order-md-1 minh-60 center_content ">
    <img src='{% if meal.image_url %}{{ meal.image_url }}{% else %}{{ meal.image_file.url }}{% endif %}'
         class="fr oh mxh-800 md-screen">
    <img src='{% if meal.image_url %}{{ meal.image_url }}{% else %}{{ meal.image_file.url }}{% endif %}'
         class="w-100 sm-screen pt-0 mt-0">
</div>

<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 order-1 order-sm-1 order-md-2 minh-60 bg-greybeige">
    <div class="right-box align-items-start nice-spacer pt-5">
        <h2 class="d-inline">{{ meal.meal_name|capfirst }} </h2>

        {% with collectors=meal.collectors.all  %}
            {% if request.user.is_authenticated %}
                {% if is_author %}
        <a href="{% url 'cards:meal_edit' meal.pk %}" ><p class="btn btn-dark mb-3">  edit</p> </a>
                {% else %}
                    <div class="sm-screen">&nbsp;</div>
                    <a href="#" data-id="{{ meal.pk }}" data-action="{% if request.user in collectors %}remove{% else %}add{% endif %}" class="collect btn btn-dark mb-3">
                        {% if request.user in collectors %}
                        remove from my collection
                        {% else %}
                        add to my collection
                    {% endif %}
                    </a>
                    <p> This meal is in <span class="collectors_count"> {{ collectors.count }} </span> collection{{ collectors.count|pluralize }} </p>

                {% endif %}

            {% else %}
                <a href="{% url 'users:login' %}?next=/meals/details/{{meal.pk}}/"><p class="btn btn-dark mb-3"> save </p></a>
            {% endif %}
        {% endwith %}
        {% if meal.meal_url %}
        <a href="{{meal.meal_url}}" class="d-block pb-2 pt-2"> Check the recipe </a>
        {% endif %}

        <hr>
        {% include 'analyzer/results_table.html' with ingredients=ingredients results=results %}
    </div>
</div>
{% endblock row %}


{% block domready %}
$('a.collect').click(function(e){
    e.preventDefault();
    $.post('{% url "cards:collect" %}', {
        'id': $(this).data('id'),
        'action': $(this).data('action')
    },
    function(data){
        if (data['status'] == 'ok'){
            var action_was = $('a.collect').data('action')
            $('a.collect').data('action', action_was == 'add' ? 'remove' : 'add');
            $('a.collect').text(action_was == 'add' ? 'Remove from my collection' : 'Add to my collection');
            var collectors_was = parseInt($('span.collectors_count').text());
            $('span.collectors_count').text(action_was == 'add' ? collectors_was+1 : collectors_was-1);
            }
    }
    );
    });

{% endblock %}

cards/templates/cards/meal/meal_create_form.html
{% load static %}
{% load cards_extras %}
{% load crispy_forms_tags %}


    <form  action="" method="POST" name="create_meal" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.non_field_errors }}

        {% for hidden_field in form_hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field|as_crispy_field }}
        {{ hidden_field.help_text }}
        {% endfor %}

        {% for field in form %}
        {% if field.name == 'image_url' %}
        {{ field.errors }}
        <span id="image_url"> {{ field|as_crispy_field }} </span>
        {{ field.help_text }}
        {% endif %}
        {% endfor %}


        {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field|as_crispy_field }}
        {% endfor %}

        {% include 'analyzer/results_table.html' with ingredients=ingr_table results=res_table %}


        <div class="text-center pt-2"><input type="submit" value="Save it" class="btn btn-dark"></div>
    </form>



        {{ form.non_field_errors }}

        {% for hidden_field in form_hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field|as_crispy_field }}
        {{ hidden_field.help_text }}
        {% endfor %}

        {% for field in form %}
        {% if field.name == 'image_url' %}
        {{ field.errors }}
        <span id="image_url"> {{ field|as_crispy_field }} </span>
        {{ field.help_text }}
        {% endif %}
        {% endfor %}


        {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field|as_crispy_field }}
        {{ field.help_text }}
        {% endfor %}






@login_required
def meal_create(request, meal_url=None, meal_name=None, ingredients_save=None, meal_images=None, results_save=None, safety=None):
    # # create the unquoted ingr and results to display results table
    # ingr_table = None
    # res_table = None
    #
    print("STARTiNG")
    data = [meal_url, meal_name, ingredients_save, meal_images, results_save, safety]
    try:
        ingr_table = parse.unquote(slug(ingredients_save, False)).split('\n')
        print('\n' * 5, 'INGR TABLE', ingr_table, type(ingr_table))
        res_table = ast.literal_eval(parse.unquote(slug(results_save, False)))
        print('\n' * 5, 'RES TABLE', res_table)
        # meal_images = parse.unquote(meal_images).split()
        # print('\n' * 5, 'IMAGES CERATE: ', request.POST.get('meal_images'))
    except AttributeError:
        print('COULD NOT GET TABLES')
        pass

    if request.POST:
        for d in data:
            print("DATA: ", d)
        if any(item is not None for item in data):
            form = MealCreateForm()
            # form = MealCreateForm()
            if meal_name != 'None':
                form.fields['meal_name'].initial = str(meal_name).replace(',', '').replace('\\n', '').replace("'", '').strip()
            # if meal_url != 'None':
            #     form.fields['meal_url'].initial = parse.unquote(meal_url)
            form.fields['ingredients'].initial = ingr_table
            form.fields['results'].initial = res_table
            # form.fields['safety'].initial = safety
        #     if meal_images != 'None':
        #         # meal_images = parse.unquote(request.POST.get('meal_images')).split()
        #         form.fields['image_file'].widget = forms.HiddenInput()
        #         form.fields['image_url'].widget = forms.HiddenInput()
        #     else:
        #         form.fields['image_url'].widget = forms.HiddenInput()
        #         meal_images = None
        else:
            form = MealCreateForm(request.POST, request.FILES)
        print(form.is_valid())
        print(form.errors)
        form.errors.clear()
        print(form.is_valid())
        if form.is_valid():
            cd = form.cleaned_data
            new_meal = form.save(commit=False)
            new_meal.author = request.user
            new_meal.save()
            new_meal.collectors.add(request.user)
            return redirect(new_meal.get_absolute_url())
        else:
            print('INVALID')
    else:
        form = MealCreateForm()

    # print('FINAL INGR TABLE: ', ingr_table)
    # print('FINAL RES TABLE: ', res_table)
    return render(request, 'cards/meal/create.html', {'form': form, 'ingr_table': ingr_table, 'res_table': res_table,
                                                      # , 'meal_images': meal_images,
                                                      })

cards/templates/cards/meal/meal_edit.html
{% extends 'main_columns.html' %}
{% load static %}
{% load analyzer_extras %}
{% load cards_extras %}

{% block row %}


<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 order-2 order-sm-2 order-md-1 minh-60 center_content bg-white">
    <img src='{% if meal.meal_file %}{{ meal.image_file.url }}{% else %}{{ meal.image_url }}{% endif %}' class="fr oh ">
</div>

<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 order-1 order-sm-1 order-md-2 minh-60 bg-greybeige ">
    <div class="right-box align-items-start p-5 ">
        <h2>Editing meal {{ meal.meal_name }}</h2>
        <form action="." method="post" name="create_meal" enctype="multipart/form-data">

            {% csrf_token %}

            {{ form.non_field_errors }}
            <h5 class="pt-3 pb-2">Meal name:</h5>
            {{ field.errors }}
            {{ form.meal_name|add_class:'w-100' }} <br>
            {{ field.help_text }}

            <h5 class="pt-3 pb-2">Meal url:</h5>
            {{ field.errors }}
            {{ form.meal_url|add_class:'w-100' }} <br>
            {{ field.help_text }}

            <h5 class="pt-3 pb-2">Meal ingredients:</h5>
<!--            show ingredients as checkboxes-->
            {{ field.errors }}
            {% for ingr in form.ingredients|add_class:'d-block'|split:","|leave_ingrs %}
            <input type="checkbox" checked=True value="{{ ingr }}" name="single_ingredients" class="bg-greybeige"> {{ingr }} <br>
            {% endfor %}
            {{ field.help_text }}

<!--            hide real ingredients, img_file and img_url field-->
            {{ form.ingredients|add_class:'d-none' }}
            {{ field.errors }}
            {{ form.results|add_class:'d-none' }}
            {{ field.help_text }}

            {{ field.errors }}
            {{ form.safety|add_class:'d-none' }}
            {{ field.help_text }}
            <br>

            <h5 class="pt-3 pb-2">Meal image:</h5>

            Upload new file:
            {{ field.errors }}
            {{ form.image_file }}
            {{ field.help_text }}<br>


            {{ field.errors }}
            {{ form.image_url|add_class:'d-none' }}
            {{ field.help_text }}<br>


            <div class="text-center pt-2"><input type="submit" value="Save changes" class="btn btn-dark"></div>
        </form>

    </div>
</div>
{% endblock row %}

cards/templates/cards/meal/meal_safety.html
{% load cards_extras %}
{% load analyzer_extras %}


{% for colour in safety|eval %}{% for key, value in colour.items %}{% for i in value|make_range %}<span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>{% endfor %}{% endfor %}{% endfor %}