analyzer/urls.py
from django.urls import path

from . import views

app_name = 'analyzer'

urlpatterns = [
    path('', views.analyze, name='analyze'),
    path('/<str:ingredients_correction>/<str:meal_url_correction>/<str:language>/', views.analyze, name='analyze'),
    path('/<str:ingredients_correction>/<str:language>/', views.analyze, name='analyze'),
]

cards/urls.py
from django.urls import include, path

from . import views

app_name = 'cards'

urlpatterns = [

    path('create/?meal_name=<str:meal_name>/?meal_url=<str:meal_url>/?ingredients=<str:ingredients>/?results=<results>/?meal_images=<meal_images>/?safety=<safety>/?tokens=<str:tokens>/',
         views.meal_create, name='meal_create'),
    path('create/', views.meal_create, name='meal_create'),
    path('details/<int:id>/', views.meal_details, name='meal_details'),
    path('edit/<int:pk>/', views.edit, name='meal_edit'),
    path('meals_list/', views.meals_list, name='meals_list'),
    path('collect/', views.collect, name='collect')


]

fodmap_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import credits

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analyzer.urls', namespace="analyzer")),
    path('credits/', credits, name='credits'),
    path('users/', include('users.urls', namespace="users")),
    path('meals/', include('cards.urls', namespace="cards")),
    path('search/', include('search.urls', namespace="search")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('search/', views.search, name='search'),


]

analyzer/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

analyzer/forms.py
from django import forms


class LanguageForm(forms.Form):
    CHOICES = [('ENG', 'English'), ('PL', 'Polski')]
    language = forms.ChoiceField(choices=CHOICES,  required=True, label='Select language: ')

class IngredientsForm(forms.Form):
    ingredients = forms.CharField(label='Ingredients: ', widget=forms.Textarea, required=False)

class LinkForm(forms.Form):
    link = forms.URLField(label='or link to the recipe: ', required=False)

search/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label='')

analyzer/views.py
from urllib import parse

from django.contrib.postgres.search import SearchVector
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from cards.models import Meal
from search.forms import SearchForm
from universal.slug import slug

from .forms import IngredientsForm, LanguageForm, LinkForm
from .utils.ingredients_checker import IngredientsChecker
from .utils.safety import calculate_safety
from .utils.scraper import Scraper
from .utils.stemmer import stemm




def get_website_data(link_form):
        scraper = Scraper()
        meal = scraper.parse(link_form['link'].value())
        meal_name = slug(str(meal.name).replace(',', '').replace('/\n', '').replace("'", '').strip(), True)
        meal_url = parse.quote(meal.url, safe='')
        meal_images = slug(str([parse.quote(img, safe='') for img in meal.images]), True) if len(meal.images) > 1 \
            else parse.quote(str(meal.images), safe='')
        return {'meal': meal, 'meal_name': meal_name, 'meal_url': meal_url, 'meal_images': meal_images}


def get_results(ingredients, language):
    checker = IngredientsChecker(ingredients)
    results, not_found, ingredients, stems = checker.check_ingredients(language)
    stems = slug(str(stems), True)
    safety = slug(str(calculate_safety(results)), True)
    safety_table = calculate_safety(results)
    return {'results': results, 'not_found': not_found, 'ingredients': ingredients, 'stems': stems, 'safety': safety,
            'safety_table': safety_table}


def analyze(request, ingredients_correction=None, meal_url_correction=None, language=None):
    meals = Meal.objects.all().order_by('-created')
    paginator = Paginator(meals, 6)
    page = request.GET.get('page')
    try:
        meals = paginator.page(page)
    except PageNotAnInteger:
        meals = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        meals = paginator.page(paginator.num_pages)
    # meals = Meal.objects.all().order_by('-created')[0:3]
    search_form = SearchForm()
    meal_data = dict()
    results_data = dict()
    ingredients_save, results_save= None, None
    language = request.POST.get('language') if not language or request.POST.get('language') != language else language
    if request.method == 'POST':
        language_form = LanguageForm(request.POST)
        ingr_form = IngredientsForm(request.POST)
        link_form = LinkForm(request.POST)
        if ingr_form.data['ingredients']:
            if ingr_form.is_valid():
                if link_form.data['link']:
                    meal_data = get_website_data(link_form)
                results_data = get_results(ingr_form['ingredients'].value(), language)
        elif link_form.data['link']:
            if link_form.is_valid():
                meal_data = get_website_data(link_form)
                results_data = get_results(meal_data['meal'].ingredients.split('\n'), language)
        if results_data:
            results_save = parse.quote(slug(str(results_data.get('results')), True), safe='')
            ingredients_save = parse.quote(slug('\n'.join(results_data.get('ingredients', '')), True), safe='')
    else:
        language_form = LanguageForm()
        ingr_form = IngredientsForm()
        link_form = LinkForm()
        if ingredients_correction:
            ingr_form.fields['ingredients'].initial = parse.unquote(slug(ingredients_correction, False))
            if meal_url_correction and meal_url_correction != "None":
                link_form.fields['link'].initial = parse.unquote(meal_url_correction)
            language_form.fields['language'].initial = language
    if request.is_ajax():
            return render(request, 'meals_list_ajax.html', {'meals': meals})
    return render(request, 'analyzer/analyze.html',
                  {'language_form': language_form, 'ingr_form': ingr_form, 'link_form': link_form, 'language': language,
                   #this is for results table
                   'ingredients': results_data.get('ingredients', None),
                   'results': results_data.get('results', None), 'not_found': results_data.get('not_found', None),
                   'safety_table': results_data.get('safety_table', None),
                   # this is for saving form
                   'meal_name': meal_data.get('meal_name', None), 'meal_url': meal_data.get('meal_url', None),
                   'meal_images': meal_data.get('meal_images', None),
                   'ingredients_save': ingredients_save, 'results_save': results_save,
                   'meals': meals, 'safety': results_data.get('safety', None),
                   'tokens': results_data.get('stems', None),
                   'search_form': search_form })


def meals_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            token = stemm(query)
            results = Meal.objects.annotate(search=SearchVector('meal_name', 'ingredients', 'tokens'),).filter(search=token[0])
            for word in token:
                results = results | Meal.objects.annotate(search=SearchVector('meal_name', 'ingredients', 'tokens'),).filter(search=word)
    return render(request, 'analyzer/search.html', {'form': form, 'query': query, 'results': results})

search/views.py
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector)
from django.shortcuts import render

from analyzer.utils.stemmer import stemm
from cards.models import Meal

from .forms import SearchForm


def search(request, ingredients_correction=None, meal_url_correction=None):
    meals = Meal.objects.all().order_by('-created')[0:3]
    form = SearchForm()
    query = None
    results = []
    if request.method == 'POST':
        if 'query' in request.POST:
            form = SearchForm(request.POST)
            if form.is_valid():
                query = form.cleaned_data['query']
                token = stemm(query)
                results = Meal.objects.annotate(search=SearchVector('meal_name', 'ingredients', 'tokens'),).filter(search=token[0])
                for word in token:
                    results = results | Meal.objects.annotate(search=SearchVector('meal_name', 'ingredients', 'tokens'),).filter(search=word)
    else:
        form = SearchForm()
    return render(request, 'search/search.html', {'form': form, 'query': query, 'results': results, 'meals': meals})

analyzer/templates/analyzer/analyze.html
{% extends 'main_columns.html' %}
{% load static %}
{% load analyzer_extras %}
{% load cards_extras %}
{% load crispy_forms_tags %}

{% block row %}

{% if results %}
<div class="col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5 order-2 order-sm-2 order-md-1 p-5 md-screen">
    <div class="h-100">
    </div>
</div>

<div class="col-12 col-sm-12 col-md-12 col-lg-7 col-xl-7 nice-spacer order-1 order-sm-1 order-md-2 minh-60 bg-greybeige">
    <div class="align-items-start">
        <br><br>
        <h3> Your results </h3>
        {% include "analyzer/results_table.html"  with safety=safety_table %}
        <p class="pt-3">Should the results be unsatisfying, try to <a href="{% url 'analyzer:analyze' ingredients_save meal_url language %}">
            correct the ingredients or change language</a> and check them again.</p>
        <div class="pt-3 text-center">
            <form class="d-inline" name="save_meal" method="post"
                  action="{% url 'cards:meal_create'%}">
                {% csrf_token %}
                <input  type="hidden" name="meal_name" value= {{meal_name}}>
                <input  type="hidden" name="meal_url" value={{meal_url}}>
                <input  type="hidden" name="ingredients" value={{ingredients_save}} >
                <input  type="hidden" name="results" value={{results_save}}>
                <input  type="hidden" name="meal_images" value={{meal_images}}>
                <input  type="hidden"  name="safety" value={{safety}}>
                <input  type="hidden"  name="tokens" value={{tokens}}>
                <input type="hidden" name="supporttype" />
                <input type="submit" value="save this meal" class="btn btn-dark d-inline"/>
            </form>
            <button type="button" class="btn btn-dark d-inline">
                <a class="text-white" href="{% url 'analyzer:analyze' %}">new check</a></button>
        </div>
    </div>
</div>

{% else %}

<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 order-2 order-sm-2 order-md-1 minh-60 md-screen" >
    <img src="{% static 'images/pineapple7.jpg' %}" class="maxw-none fr ">
</div>

<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 nice-spacer order-1 order-sm-1 order-md-2 minh-60 bg-greybeige ">
    <h5 class="text-center"> Check whether your meal is low fodmap safe </h5>
    <form action='#' method="post">
        {{ ingr_form|crispy }}
        {{ link_form|crispy }}
        <div id="language">{{ language_form|crispy }}</div>
        {% csrf_token %}
        <input type="submit" value="Check it!" class="btn btn-dark">
    </form>
</div>

{% endif %}

{% endblock row %}

{% block content %}
<h2 class="text-center pt-5 font-spectral"> {% if user.is_authenticated %} {{ user.username }}{% else %} hey you{% endif %}, look at all the food you can eat</h2>
<hr>
<div class="container text-center mb-3">
    <form action="{% url 'search:search' %}" method="post">
        <p class="text-center d-inline m-1"> search meals by ingredients: </p>
        {% for field in search_form %}
        {{ field_errors }}
        <span class="d-inline">{{ field }}</span>
        {% csrf_token %}
        {% endfor %}
        <input type="submit" value="Search" class="btn btn-dark d-inline m-1 ml-2">
    </form>
</div>

<div class="container">
    <div class="row" id="meals-row">
        {% for meal in meals %}
        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 pb-3 pt-3 text-center hover-dark">
            <a href="{{ meal.get_absolute_url }}">
                <img src="{{ meal.image_file.url }}"
                     class="img-thumb" alt="{{ meal.meal_name|capfirst }}"> </a>
            <p class="mt-3">{% include 'cards/meal/meal_safety.html' with safety=meal.safety %} </p>
            <a href="{{ meal.get_absolute_url }}"><p class="text-dark">{{ meal.meal_name }} </p></a>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock content %}

{% block domready %}
var page = 1;
var empty_page = false;
var block_request = false;
$(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data) {
            if(data == '') {
                empty_page = true;
            } else {
                block_request = false;
                $('#meals-row').append(data);
            }
        });
    }
});
{% endblock %}

analyzer/templates/analyzer/results_table.html
{% load analyzer_extras %}

<h5 class="mt-3">Meal safety: {% include 'cards/meal/meal_safety.html' %} </h5>

<table class="table table-striped">
    <thead class="md-screen">
    <tr>
        <th scope="col"></th>
        <th scope="col">Ingredient</th>
        <th scope="col">Max amount</th>
        <th scope="col">Comment</th>
        <th scope="col">Substitute</th>
    </tr>
    </thead>
    <tbody>
    {% for ingr in ingredients %}
    {% for res, amount, comment, safety, substitute in results %}
    {% if ingr == res %}
    <tr class="md-screen">
        <th scope="row" class="bg-{{safety}}"></th>
        <td>{{ ingr }} </td>
        <td>{{ amount }} </td>
        <td>{% if safety == 'blue' %} change to {% else %} {{ comment }} {% endif %} </td>
        <td>{% if substitute is not None %} {{ substitute }} {% endif %}  </td>
    </tr>
    <tr class="sm-screen">
        <td class="bg-{{safety}} text-center">{{ ingr }}
            {% if amount %}<br> <hr> max amount: {{ amount }}{% endif %}
            {% if safety == 'blue' %} <br> <hr> change to {% else %} {{ comment }} {% endif %}{% if substitute is not None %} {{ substitute }} {% endif %}
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    {% endfor %}
    </tbody>
</table>



<div class="sm-screen">&nbsp;</div>
<div class="row whitespace no-gutters">
    <div class="col bg-green text-center pl-1 pr-1">safe</div>
    <div class="col bg-yellow text-center pl-2 pr-2">be careful with the amount</div>
    <div class="col bg-orange text-center pl-2 pr-2"> very little amount is ok</div>
    <div class="col bg-red text-center pl-1 pr-1">not safe</div>
    <div class="col bg-blue text-center pl-2 pr-2">choose a substitute instead</div>
    <div class="col bg-grey text-center pl-1 pr-1">could not find this</div>
</div>

analyzer/templates/analyzer/safety.html
{% load static %}
{% load analyzer_extras %}

{{ safety_colors }}
  <h5>Meal safety:
         {% for colour in safety%}
         {{ colour }}
         {% for key, value in colour.items %}
         {{ key || {{ value }}
         {% for i in value|make_range %}
         <span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>
         {% endfor %}{% endfor %}{% endfor %} </h5>
       <h5>Meal safety: {% for colour in safety%}{% for key, value in colour.items %}{% for i in value|make_range %}<span class="bg-{{ key }} d-inline p-0 m-0" >&nbsp;&nbsp;&nbsp;</span>{% endfor %}{% endfor %}{% endfor %} </h5>

analyzer/templates/analyzer/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

{% if query %}
<p> Meals containing: {{ query ]}</p>
{% with results_count as total_results %}
Found {{ total_results }} meal{{ total_results|pluralize }}
{% endwith %}

<div class="container">
    <div class="row">
        {% for meal in results %}
        {{ meal.name }}
        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 pb-3 pt-3 text-center hover-dark">
            <a href="{{ meal.get_absolute_url }}">
                <img src="{{ meal.image_file.url }}"
                     class="img-thumb" alt="{{ meal.meal_name|capfirst }}" id="meal_image_url"> </a>
            <p class="mt-3">{% include 'cards/meal/meal_safety.html' with safety=meal.safety %} </p>
            <a href="{{ meal.get_absolute_url }}"><p id="meal_name">{{ meal.meal_name }} </p></a>
        </div>
    </div>
</div>
{% empty %}
There are no results
{% endfor %}

{% else %}

<p> Search meals </p>
<form action="." method="get">
    {{ form|crispy }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock content %}